Kw fuature#67
sora-jbk/quizoo pull request #69
Opened 2023-11-22 01:25 UTC by wataru-51

close #67

2023-11-27 01:05 UTC, sora-jbk commented on quizoo/src/main/java/db/bean/AnswerhistoryBean.java
>  	private int quizId;
QuizBeanを持たせる

2023-11-27 01:07 UTC, sora-jbk commented on quizoo/src/main/java/db/bean/AnswerhistoryBean.java
>  	private int quizId;
answered_time,question_count,correct_countを持たせる

2023-11-27 01:09 UTC, sora-jbk commented on quizoo/src/main/java/db/dao/AnswerHistoryDao.java
> +
QuizBeanをインスタンス化してAnswerhistoryBeanにセット

2023-11-27 06:21 UTC, sora-jbk requested changes

2023-11-27 06:21 UTC, sora-jbk commented on quizoo/src/main/java/db/bean/AnswerhistoryBean.java
> +	public AnswerhistoryBean(String answeredTime, int questionCount, int correctCount) {
QuizBeanも引数に必要

2023-11-28 02:07 UTC, wataru-51 commented
よいしょ！
みてくれよ！

2023-11-28 02:07 UTC, wataru-51 commented
あーよいしょーー

2023-11-29 06:42 UTC, sora-jbk approved these changes

2023-11-29 06:42 UTC, merged